### ISSUE TITLE
Unlimited number of batches

### ISSUE THREAD

**Issue by orginux** [orginux/kafka-traffic-generatror#1]
this allows us to generate messages until the program is stopped:
```yaml
  batch_msgs: 0
  batch_count: 10
  batch_delay_ms: 1000
```
